name: arrow_maze_cliente_copy
description: Arrow Maze - Escape Puzzle game client.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.0
