import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations({required this.locale});

  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'gameTitle': 'Arrow Maze',
      'levelSelect': 'Select Level',
      'victory': 'Victory!',
      'defeat': 'Defeat',
      'gameOver': 'Game Over',
      'retry': 'Retry',
      'backToLevels': 'Back to Levels',
      'backToMenu': 'Back to Menu',
      'backToLogin': 'Back to Login',
      'moves': 'Moves',
      'score': 'Score',
      'pause': 'Pause',
      'resume': 'Resume',
      'hint': 'Hint',
      'tapArrowToDestroy': 'Tap an arrow to destroy it',
      'cancel': 'Cancel',
      'hammer': 'Hammer',
      'magnet': 'Magnet',
      'coins': 'Coins',
      'loading': 'Loading...',
      'loadingLevels': 'Loading levels...',
      'noLevelsAvailable': 'No levels available',
      'noLeaderboardData': 'No leaderboard data',
      'error': 'Error',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'username': 'Username',
      'leaderboard': 'Leaderboard',
      'settings': 'Settings',
      'language': 'Language',
      'languageSubtitle': 'English / Español',
      'logout': 'Logout',
      'level': 'Level',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'paused': 'Paused',
      'restart': 'Restart',
      'sound': 'Sound',
      'music': 'Music',
      'vibration': 'Vibration',
      'preloadAllTitle': 'Download all levels?',
      'preloadAllMessage':
          'You can download every level\'s board now so they open instantly later, or keep downloading them one by one as you play.',
      'notNow': 'Not now',
      'downloadAll': 'Download all',
      'downloadingLevels': 'Downloading levels...',
      'home': 'Home',
      'play': 'Play',
      'profile': 'Profile',
      'globalLeaderboard': 'Global',
      'perLevel': 'By Level',
      'selectAvatar': 'Choose your avatar',
      'levelsCompleted': 'Levels',
      'totalScore': 'Total Score',
      'biometricIdentification': 'Biometric Identification',
      'notEnoughCoins': 'Not enough coins',
      'hintName': 'Hint',
      'hintDescription': 'Highlights an arrow that can exit right now.',
      'gridName': 'Grid',
      'gridDescription': 'Shows where each arrow on the board exits to.',
      'hammerName': 'Hammer',
      'hammerDescription': 'Tap any arrow on the board to destroy it, even if blocked.',
      'magnetName': 'Magnet',
      'magnetDescription': 'Removes up to 5 arrows that can already exit the board.',
      'emailRequired': 'Email is required',
      'emailMustHaveAt': 'Email must contain exactly one @',
      'emailTooShort': 'Email must have more than 3 characters before @',
      'emailInvalidChars': 'Email contains invalid characters (only . and _ are allowed)',
      'emailInvalidFormat': 'Invalid email format',
      'usernameRequired': 'Username is required',
      'usernameTooShort': 'Username must have at least 3 characters',
      'usernameInvalidChars': 'Username contains invalid characters (only . and _ are allowed)',
      'usernameInvalidFormat': 'Username can only contain letters, numbers, . and _',
      'invalidEmailOrUsername': 'Enter a valid email or username',
      'passwordMinLength': '8 characters minimum',
      'passwordNeedsUpperCase': '1 uppercase letter',
      'passwordNeedsSpecialChar': '1 special character',
      'passwordRequirements': 'Password Requirements',
      'passwordRequiresMinLength': 'At least 8 characters',
      'passwordRequiresUpperCase': 'At least 1 uppercase letter',
      'passwordRequiresSpecialChar': 'At least 1 special character (@#\$%^&*)',
      'lifeLost': 'You lost a life',
      'livesRemaining': 'Lives remaining',
      'nextLifeIn': 'Next life in',
      'exitLevelTitle': 'Leave the level?',
      'exitLevelMessage': 'Leaving now counts as a defeat and you will lose a life.',
      'keepPlaying': 'Keep playing',
      'leaveAnyway': 'Leave',
      'noLivesTitle': 'Out of lives',
      'noLivesMessage': 'You have no lives left. Wait for the next one or buy one with coins.',
      'buyLife': 'Buy life',
      'lifePurchaseFailed': 'Not enough coins to buy a life',
      'emailOrUsername': 'Email or username',
      'board3d': '3D board',
      'board3dDescription': 'View the board in perspective — drag to spin it, long-press to recenter',
      'game3d': '3D game (6 directions)',
      'game3dDescription': 'Boards become 4-layer prisms shown in cascade — arrow bodies cross between floors',
      'showSkeleton': 'Show board skeleton',
      'hexBoard': 'Hexagonal board',
      'hexBoardDescription': 'A practice board where every cell connects in 6 directions — free power-ups, no coins',
      'hexBoardSimple': 'Simple',
      'hexBoardSimpleSubtitle': 'Small hexagon',
      'hexBoardComplex': 'Complex',
      'hexBoardComplexSubtitle': 'Large ring with a hole in the middle',
      'hexBoardArrowsLeft': 'arrows',
      'hexBoardMovesLeft': 'moves',
      'hexBoardCleared': '🎉 Board cleared!',
      'hexBoardStuck': '💀 No way out',
      'hexBoardScoreLabel': 'Score',
      'hexBoardReasonLabel': 'Reason',
      'newBoard': 'New board',
      'freePowerUpsNote': 'Free power-ups — practice mode, no coins',
      'playerBoards': 'Player boards',
      'communityBoards': 'Community',
      'myBoards': 'Mine',
      'createBoard': 'Create board',
      'chooseSize': 'Choose a size',
      'sizeSmall': 'Small',
      'sizeMedium': 'Medium',
      'sizeLarge': 'Large',
      'arrows': 'arrows',
      'cells': 'cells',
      'drawHint': 'Tap or drag to draw your board',
      'boardName': 'Board name',
      'publishBoard': 'Publish board',
      'boardSaved': 'Board published!',
      'boardTooSmall': 'Mark at least 10 cells',
      'boardNameTooShort': 'Name must have at least 3 characters',
      'boardSaveFailed': 'Could not publish the board',
      'addBoard': 'Add',
      'noCommunityBoards': 'No boards yet — create the first one!',
      'noMyBoards': 'You haven\'t added any boards yet',
      'byAuthor': 'by',
      'deleteBoard': 'Delete',
      'deleteBoardTitle': 'Delete this board?',
      'deleteBoardMessage': 'It will be removed from the community for everyone.',
      'boardDeleted': 'Board deleted',
      'boardDeleteFailed': 'Could not delete the board',
      'Email already registered': 'Email already registered',
      'Username already registered': 'Username already registered',
      'Email already exists': 'Email already exists',
      'Username already exists': 'Username already exists',
      'User already exists': 'User already exists',
      'Invalid credentials': 'Invalid credentials',
    },
    'es': {
      'gameTitle': 'Laberinto de Flechas',
      'levelSelect': 'Seleccionar Nivel',
      'victory': '¡Victoria!',
      'defeat': 'Derrota',
      'gameOver': 'Fin del Juego',
      'retry': 'Reintentar',
      'backToLevels': 'Volver a Niveles',
      'backToMenu': 'Ir al inicio',
      'backToLogin': 'Volver a login',
      'moves': 'Movimientos',
      'score': 'Puntuación',
      'pause': 'Pausa',
      'resume': 'Reanudar',
      'hint': 'Pista',
      'tapArrowToDestroy': 'Toca una flecha para destruirla',
      'cancel': 'Cancelar',
      'hammer': 'Martillo',
      'magnet': 'Imán',
      'coins': 'Monedas',
      'loading': 'Cargando...',
      'loadingLevels': 'Cargando niveles...',
      'noLevelsAvailable': 'No hay niveles disponibles',
      'noLeaderboardData': 'No hay datos de tabla de clasificación',
      'error': 'Error',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'email': 'Correo',
      'password': 'Contraseña',
      'username': 'Usuario',
      'leaderboard': 'Tabla de clasificación',
      'settings': 'Configuración',
      'language': 'Idioma',
      'languageSubtitle': 'English / Español',
      'logout': 'Cerrar sesión',
      'level': 'Nivel',
      'easy': 'Fácil',
      'medium': 'Medio',
      'hard': 'Difícil',
      'paused': 'Pausa',
      'restart': 'Reiniciar',
      'sound': 'Sonido',
      'music': 'Música',
      'vibration': 'Vibración',
      'preloadAllTitle': '¿Descargar todos los niveles?',
      'preloadAllMessage':
          'Podés descargar el tablero de todos los niveles ahora para que abran al instante después, o seguir descargándolos de a uno mientras jugás.',
      'notNow': 'Ahora no',
      'downloadAll': 'Descargar todos',
      'downloadingLevels': 'Descargando niveles...',
      'home': 'Inicio',
      'play': 'Jugar',
      'profile': 'Perfil',
      'globalLeaderboard': 'Global',
      'perLevel': 'Por nivel',
      'selectAvatar': 'Elige tu avatar',
      'levelsCompleted': 'Niveles',
      'totalScore': 'Puntaje total',
      'biometricIdentification': 'Identificación biométrica',
      'notEnoughCoins': 'No tienes suficientes monedas',
      'hintName': 'Pista',
      'hintDescription': 'Resalta una flecha que puede salir ahora mismo.',
      'gridName': 'Cuadrícula',
      'gridDescription': 'Muestra hacia dónde sale cada flecha del tablero.',
      'hammerName': 'Martillo',
      'hammerDescription': 'Toca cualquier flecha del tablero para destruirla, incluso si está bloqueada.',
      'magnetName': 'Imán',
      'magnetDescription': 'Elimina hasta 5 flechas que ya pueden salir del tablero.',
      'emailRequired': 'El correo es requerido',
      'emailMustHaveAt': 'El correo debe contener exactamente un @',
      'emailTooShort': 'El correo debe tener más de 3 caracteres antes del @',
      'emailInvalidChars': 'El correo contiene caracteres no permitidos (solo . y _ están permitidos)',
      'emailInvalidFormat': 'Formato de correo inválido',
      'usernameRequired': 'El usuario es requerido',
      'usernameTooShort': 'El usuario debe tener al menos 3 caracteres',
      'usernameInvalidChars': 'El usuario contiene caracteres no permitidos (solo . y _ están permitidos)',
      'usernameInvalidFormat': 'El usuario solo puede contener letras, números, . y _',
      'invalidEmailOrUsername': 'Ingresa un correo o usuario válido',
      'passwordMinLength': '8 caracteres mínimo',
      'passwordNeedsUpperCase': '1 mayúscula',
      'passwordNeedsSpecialChar': '1 carácter especial',
      'passwordRequirements': 'Requisitos de contraseña',
      'passwordRequiresMinLength': 'Al menos 8 caracteres',
      'passwordRequiresUpperCase': 'Al menos 1 mayúscula',
      'passwordRequiresSpecialChar': 'Al menos 1 carácter especial (@#\$%^&*)',
      'lifeLost': 'Perdiste una vida',
      'livesRemaining': 'Vidas restantes',
      'nextLifeIn': 'Próxima vida en',
      'exitLevelTitle': '¿Salir del nivel?',
      'exitLevelMessage': 'Salir ahora cuenta como derrota y perderás una vida.',
      'keepPlaying': 'Seguir jugando',
      'leaveAnyway': 'Salir',
      'noLivesTitle': 'Sin vidas',
      'noLivesMessage': 'No te quedan vidas. Espera la próxima o compra una con monedas.',
      'buyLife': 'Comprar vida',
      'lifePurchaseFailed': 'No tienes monedas suficientes para comprar una vida',
      'emailOrUsername': 'Correo o usuario',
      'board3d': 'Tablero 3D',
      'board3dDescription': 'Ver el tablero en perspectiva — arrastra para girarlo, mantén presionado para centrarlo',
      'game3d': 'Juego 3D (6 direcciones)',
      'game3dDescription': 'Los tableros se vuelven prismas de 4 capas en cascada — los cuerpos de las flechas atraviesan los pisos',
      'showSkeleton': 'Ver esqueleto del tablero',
      'hexBoard': 'Tablero hexagonal',
      'hexBoardDescription': 'Un tablero de práctica donde cada celda conecta en 6 direcciones — comodines gratis, sin monedas',
      'hexBoardSimple': 'Simple',
      'hexBoardSimpleSubtitle': 'Hexágono pequeño',
      'hexBoardComplex': 'Complejo',
      'hexBoardComplexSubtitle': 'Anillo grande con un hueco en el centro',
      'hexBoardArrowsLeft': 'flechas',
      'hexBoardMovesLeft': 'movimientos',
      'hexBoardCleared': '🎉 ¡Tablero despejado!',
      'hexBoardStuck': '💀 Sin salida',
      'hexBoardScoreLabel': 'Puntaje',
      'hexBoardReasonLabel': 'Motivo',
      'newBoard': 'Nuevo tablero',
      'freePowerUpsNote': 'Comodines gratis — modo práctica, sin monedas',
      'playerBoards': 'Tableros de jugadores',
      'communityBoards': 'Comunidad',
      'myBoards': 'Míos',
      'createBoard': 'Crear tablero',
      'chooseSize': 'Elige un tamaño',
      'sizeSmall': 'Pequeño',
      'sizeMedium': 'Mediano',
      'sizeLarge': 'Grande',
      'arrows': 'flechas',
      'cells': 'celdas',
      'drawHint': 'Toca o arrastra para dibujar tu tablero',
      'boardName': 'Nombre del tablero',
      'publishBoard': 'Publicar tablero',
      'boardSaved': '¡Tablero publicado!',
      'boardTooSmall': 'Marca al menos 10 celdas',
      'boardNameTooShort': 'El nombre debe tener al menos 3 caracteres',
      'boardSaveFailed': 'No se pudo publicar el tablero',
      'addBoard': 'Agregar',
      'noCommunityBoards': 'Aún no hay tableros — ¡crea el primero!',
      'noMyBoards': 'No has agregado tableros todavía',
      'byAuthor': 'por',
      'deleteBoard': 'Eliminar',
      'deleteBoardTitle': '¿Eliminar este tablero?',
      'deleteBoardMessage': 'Se quitará de la comunidad para todos.',
      'boardDeleted': 'Tablero eliminado',
      'boardDeleteFailed': 'No se pudo eliminar el tablero',
      'Email already registered': 'El correo electrónico ya está registrado',
      'Username already registered': 'El nombre de usuario ya está registrado',
      'Email already exists': 'El correo electrónico ya está registrado',
      'Username already exists': 'El nombre de usuario ya está registrado',
      'User already exists': 'El usuario ya está registrado',
      'Invalid credentials': 'Credenciales inválidas',
    },
  };

  static const supportedLocales = [
    Locale('en', ''),
    Locale('es', ''),
  ];

  String translate(String key) {
    final languageCode = locale.languageCode;
    return _localizedStrings[languageCode]?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(locale: const Locale('en', ''));
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale: locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
